const fs = require('fs');

const filePaths = ['client/src/pages/ProjectDetail1.tsx', 'client/src/pages/ProjectDetail2.tsx', 'client/src/pages/ProjectDetail3.tsx'];

filePaths.forEach(filePath => {
  let content = fs.readFileSync(filePath, 'utf-8');

  // Fix the syntax error in the string replacement that was generated by the previous script
  content = content.replace(
    /\{\!\s*hideHeader\s*&&\s*\(\s*(<h2 className="text-\[32px\] md:text-\[40px\] font-bold mb-6 leading-\[1\.3\] tracking-tight font-sans">[\s\S]*?<\/h2>)\s*\)\}/g,
    '{!hideHeader && ( $1 )}'
  );

  // We also need to fix the banner image error: 'Case1' and '/c3-hero.png' are literal strings in the previous script but need to be JSX variables or strings.
  // Wait, let's just do a clean regex replacement for the banner if it's broken.

  fs.writeFileSync(filePath, content, 'utf-8');
});
